# Generated by Django 4.1.3 on 2022-11-25 22:44

import base.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.CharField(default=base.utils.model_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=base.utils.art_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default=base.utils.model_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(default=base.utils.model_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('amount', models.PositiveIntegerField()),
                ('max_com', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.CharField(default=base.utils.model_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('time_start', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('on_voting', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='base.artist')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(default=base.utils.model_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('reward', models.FloatField(default=0)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.art')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.artist')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='base.artist'),
        ),
        migrations.AddField(
            model_name='art',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='base.show'),
        ),
    ]
