# Generated by Django 4.1.3 on 2022-12-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_vote_is_finished_remove_vote_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='show',
        ),
        migrations.AlterField(
            model_name='artist',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
