# Generated by Django 4.1.3 on 2022-12-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_art_artist_remove_vote_show_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='last_update',
            new_name='last_vote',
        ),
    ]
