# Generated by Django 4.1.3 on 2022-12-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_last_update_show_last_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='reward',
        ),
        migrations.AddField(
            model_name='vote',
            name='reward',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
